# Generated by Django 6.0.5 on 2026-08-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='News title or short caption.', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('post_type', models.CharField(choices=[('photo', 'Photo Only'), ('article', 'Photo + Description')], default='article', max_length=20)),
                ('image', models.ImageField(help_text='Main image for this news post.', upload_to='news/')),
                ('image_alt', models.CharField(blank=True, help_text='SEO-friendly alternative text for the image.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='News description. Leave empty for photo-only posts.')),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword you want this news post to target.', max_length=150)),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated related SEO keywords.', max_length=500)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('seo_score', models.PositiveIntegerField(default=0, help_text='Internal SEO content score from 0 to 100.')),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt', models.TextField(blank=True, help_text='Prompt used to generate the description.')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
