# Generated by Django 6.0.5 on 2026-08-08 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='image_alt',
            field=models.CharField(blank=True, help_text='SEO-friendly alternative text for the main image.', max_length=255),
        ),
        migrations.CreateModel(
            name='NewsPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('image_alt', models.CharField(blank=True, help_text='SEO-friendly alt text for this image.', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Optional caption displayed below the image.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the order of gallery images.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app.newspost')),
            ],
            options={
                'verbose_name': 'News Gallery Image',
                'verbose_name_plural': 'News Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
