# Generated by Django 6.0.5 on 2026-10-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_newspost_image_alt_newspostimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='video',
            field=models.FileField(blank=True, help_text='Upload an MP4, WebM or compatible video file.', null=True, upload_to='news/videos/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='description',
            field=models.TextField(blank=True, help_text='News description. Supports rich text formatting.'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for this news post.', null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_type',
            field=models.CharField(choices=[('photo', 'Photo Only'), ('article', 'Photo + Description'), ('video', 'Video + Description')], default='article', max_length=20),
        ),
    ]
